### ISSUE TITLE
Research, Document and Update Lovelace Dashboard in Cloud HA

### ISSUE THREAD

**Issue by scottdear** [oceanbuilders/smartpod#10]
I saw an integration that allows customization of the Lovelace dashboard., work w/ @angiedear to get graphic assets and additional requirements.

Acceptance Criteria
---------------------

1. Documentation, step by step on pieces needed to install the customizations in a stock HA instance.
2. Updates to cloud instance w/ changes in 1
3. Test deployment to Nana Spot.

**Comment by scottdear** [comment]
log in to admin instances w/ nodejs via ssh.
add mac public key to .ssh/authorized_keys
ping @scottdear

**Comment by scottdear** [comment]
@angiedear needs to get assets, icons images, and color RGB values to use.

**Comment by scottdear** [comment]
The assets images, etc. is on https://github.com/oceanbuilders/SmartHome/issues/1

**Comment by angiedear** [comment]
[https://wiki.oceanbuilders.com/books/general/page/brand-guidelines](url)

**Comment by godslave05** [comment]
Instructions needs to be write down here for basic theme integration
-------
