### ISSUE TITLE
Shower controller for 3 exits and shower pump

### ISSUE THREAD

**Issue by omerll** [oceanbuilders/smartpod#101]
Integrate 3 on-off stainless steel valve to control the flow of water from 3 exits with isolated TRIACs and shower pump:
-Shower Head
-Hand Held Shower
-6 massage jets

write automation turn on the shower pump if any of the exits are open
write automation turn off shower pump if all the exits are off

Integrate everything into homeassistant

**Comment by amitpujar** [comment]
Done!
