### ISSUE TITLE
Design and Build Bilge Pump System

### ISSUE THREAD

**Issue by omerll** [oceanbuilders/smartpod#106]
Requirements in this design document made by omer 
-Has to overcome more than 4 m with a flow of 1500 GPH
-Corrosion resistant
-High Efficency motor
-Capacitive sensor to protect the pump to run dry

[Bildge Pumo Documentation.pdf](https://github.com/oceanbuilders/smartpod/files/7599106/Bildge.Pumo.Documentation.pdf)

**Comment by omerll** [comment]
Pump was selected with the folowing specs:
![WhatsApp Image 2021-11-24 at 17 16 05](https://user-images.githubusercontent.com/84348234/143324653-0b3cd8cb-9bd8-44ce-8523-54fed640fb53.jpeg)
Powerful sump pump: 750 W, 1 HP motor. Maximum elevation: 16 feet; 3302 gallons per hour tackles any drainage job in a fraction of the time. This pump easily passes solids up to 1 inch in diameter. Ideal for flooded areas or  bilges.
High-quality materials: Thermoplastic composite material is highly resistant. Designed and manufactured according to valid safety requirements. The thermoplastic body resists corrosion as there are no exposed metal parts. Lower noise and energy efficiency. Oil-free engine that does not require maintenance.
Automatic float switch: start / stop automatically. When the water level is lower than 4.7 inches, it will automatically disconnect the power; when the water level rises above 4.7 inches, the pump will start again. Immediately cut off when the pump does not pump water to prevent the coil from burning.

Cost of the bildge pump 60 USD

**Comment by omerll** [comment]
Height Test for the Bildge pump with 6 meter pipe =)

https://user-images.githubusercontent.com/84348234/143324804-dfc7056c-fe79-4b92-aa90-6718c08ea410.mp4

**Comment by omerll** [comment]
FPGA & Water level sensor will be orded today

**Comment by omerll** [comment]
Water level sensor : arrived
![WhatsApp Image 2021-11-26 at 16 11 28](https://user-images.githubusercontent.com/84348234/144090159-fb3513e8-80ba-465a-8dc8-1dac31449088.jpeg)

**Comment by omerll** [comment]
Video :
https://user-images.githubusercontent.com/84348234/144090471-bac3c27b-3743-4919-8e4d-578c47f1729a.mp4

**Comment by omerll** [comment]
3D printed mount and explanation:
https://user-images.githubusercontent.com/84348234/144459646-50ba32e6-92df-4bcf-bbbe-83820dda366c.mp4

**Comment by omerll** [comment]
Why I don't want to use FPGA:

- The FPGA is only digital so for our application it will require to buy extra Hardware such as ADC (Analog to Digital Converter), a DAC (Digital to Analog Converter) and a signal conditioning for the sensors.

-It will require more time to develop the project because of the HDL (Hardware Description Language) programming, and the HA integration will required also more time to develop.

-There is a shortage on FPGA because of the silicon shortage imput.

-Adding all above the cost is expensive: the FPGA costs $207.00USD
the DAC costs $40.00USD
the signal conditioning cost $10.00USD


Why I want to use a PLC Logo:

-The integration with HA is already done and had taken 2 weeks of work from me.

-Therefore, the integration and programming will take less time to develop.

-The PLC has an ADC and DAC integrated so it doesnt requires extra HW.
-The PLC are the controllers that we use in the industry for more than 40 years so is a more reliable controller.

-The PLC has escalability for more Bilges and sensors.

-It is less expensive than FPGA: costs $174.47USD
- and $18.50USD for Software.

**Comment by omerll** [comment]
PLC Logo was approved by Grant.
PLC Logo was ordered, will arrive on 4/Dec/2021

**Comment by siddiqss** [comment]
The PLC program was completed and working as expected.
The water level sensor was linearized and caliberated to measure from 0 to 5 meters. The SSR was installed. 
The custom integration with HA is also done.

The UI for PLC was also done.
Ordered a den rail and currently 3D printing the custom case for bilge pump controller.

**Comment by omerll** [comment]
System working correctly and acomplishing all the requierments , test and demo was made, Controller was assabled into his 3D printed case 
Proyect done

**Comment by omerll** [comment]
Write new issue for documentation
