### ISSUE TITLE
Store SeaPod Data efficiently in Dynamo DB and integrate with Frontend

### ISSUE THREAD

**Issue by omerll** [oceanbuilders/smartpod#108]
Acceptance criteria:
- Compatible with home assistant 
- Light weight and efficent
- Install database on AWS server and a backed webservice for receiving data from each pod
-

**Comment by siddiqss** [comment]
Created a new table in DynamoDB. Calling POST request from HA to API GW and storing entities in the table.

**Comment by siddiqss** [comment]
HA dev server is sending dummy data to dynamo db by POST request. The frontend is fetching the SeaPod Data from dynamo db using GET request. Currently facing problem with db query.

**Comment by omerll** [comment]
Omer and Talha will set up the config for fetching data from Panama server also

**Comment by siddiqss** [comment]
Integrated the dev server in Panama with the APIs and it's storing data in DynamoDB.
The data is being fetched by the frontend dashboard.
