### ISSUE TITLE
Redesign, 3D print, Build and Test Separator for Black Water system

### ISSUE THREAD

**Issue by omerll** [oceanbuilders/smartpod#109]
Build the first prototype for the separator
Install poop weight sensors
Install Electric Piston
Design and Build PCB and eletronic design 
Write firmware for microcontroller

**Comment by amitpujar** [comment]
Separator was built from all the 3D printed parts with screws and epoxy resin to seal the system.
2 weight sensors were installed. The grid was installed successfully. Piston-mounting piece was redesigned.

**Comment by siddiqss** [comment]
The piston mounting piece was 3D printed. 42 hours of printing. Still in progress.

**Comment by omerll** [comment]
Piston mounting piece was printed and iinstalled
Currently soldering the wright sensors to the electronic board and signal conditioning circuit

**Comment by omerll** [comment]
![WhatsApp Image 2021-12-14 at 10 19 54](https://user-images.githubusercontent.com/84348234/146038719-6f9b5284-8a92-4d54-8ab8-723e21012e0e.jpeg)

**Comment by omerll** [comment]
![WhatsApp Image 2021-12-14 at 10 20 07](https://user-images.githubusercontent.com/84348234/146038732-790b6928-ed19-45af-8b3f-8d75d6f521e8.jpeg)

**Comment by godslave05** [comment]
work in progress

**Comment by siddiqss** [comment]
Will redesign wall mount for the separator and printing new parts.

**Comment by omerll** [comment]
![WhatsApp Image 2021-12-16 at 10 16 07](https://user-images.githubusercontent.com/84348234/146408628-f6d22cd3-ed94-4fd6-875e-a38425a9c116.jpeg)

**Comment by siddiqss** [comment]
The 3D printed wall-mount was assembled and mounted.
Separator is calibrated and ready to use.

**Comment by omerll** [comment]
![demo4](https://user-images.githubusercontent.com/84348234/147365457-24e575fd-b924-46f3-b605-506e381b5cda.jpg)
![demo3](https://user-images.githubusercontent.com/84348234/147365469-f2a28b50-087f-4498-9083-8c5d76a2c4aa.jpg)

**Comment by omerll** [comment]
Test with real poop: https://drive.google.com/file/d/1D9FLHr9E6XiLOSCc9LbiOdnuG7TzKbWp/view?usp=sharing
