### ISSUE TITLE
Access to additional Raspberry Pi for installation and testing of MyPod application

### ISSUE THREAD

**Issue by amitpujar** [oceanbuilders/smartpod#111]
Grant mentioned that there are some Pis are available in Panama for testing/installation. Omer to get in touch with Craig Lewis.

**Comment by amitpujar** [comment]
1. Grant has some unused Raspberry Pi in Panama (Craig can help set up).
2. Omer to contact Craig over WhatsApp to take it forward. (Craig has the context - Amit's email dated Dec 3rd)

**Comment by omerll** [comment]
This issue was solved on 27 of dec!
Raspberry pi is running in panama with custom software and VPN network for remote acess!
If you need credentials to this server oing me on discord!
