### ISSUE TITLE
GET/POST/UPDATE/DELETE SeaPod data from Dynamo DB 

### ISSUE THREAD

**Issue by siddiqss** [oceanbuilders/smartpod#112]
Create a table in Dynamo DB. 
Create API with API Gateway to trigger lambda.
Create a lambda function to GET/POST/UPDATE/DELETE SeaPods data from Dynamo DB.

**Comment by siddiqss** [comment]
Created the form for registering the seapods from frontend.
Learning Dynamo DB.

**Comment by godslave05** [comment]
work in progress

**Comment by siddiqss** [comment]
Created PUT and DELETE endpoints in API GW. Updated lambda function "crudSeapod" which updates seapod details in DynamoDB.

Replaced Table with Data Grid in the frontend. Admins can now edit the SeaPods details from Data Grid and click save button which will call PUT endpoint which will trigger lambda to save new details. 

Managing state for SeaPods details. If admin goes to other tabs and comes back to "Manage SeaPod" tab, the state will be preserved and instead of again calling the API, Data Grid will persist it's state.

**Comment by godslave05** [comment]
I am wondering why are we doing redundant task here . Doesn't this same task is described here ?
https://github.com/oceanbuilders/smartpod/issues/28

**Comment by siddiqss** [comment]
@godslave05 Using same API "SeaPodREST" that you created but it only had GET method. No POST/PUT/DELETE method was present. Enabled CORS so that communication with Browsers is secured. Also using Cognito Authorizer instead of Lambda Authorizer. Created a new table in DynamoDB. Previous table had only two attributes (ID and Port Number which I don't think we will use since SSH tunneling approach doesn't work for now). Integrated this API with frontend (admin panel).
