### ISSUE TITLE
Build Insulated Hot Water Tank

### ISSUE THREAD

**Issue by omerll** [oceanbuilders/smartpod#114]
- Build a hot water tank in 2 sections, with polyuratane an fiber glass 
-The tank should mantain is tempetraturre over time

**Comment by omerll** [comment]
![WhatsApp Image 2021-12-16 at 10 17 07](https://user-images.githubusercontent.com/84348234/146408899-cb0809d3-71bf-43f5-8235-38c9b4e7ce88.jpeg)

**Comment by omerll** [comment]
![WhatsApp Image 2021-12-16 at 10 16 31](https://user-images.githubusercontent.com/84348234/146408921-cd91f837-8522-4a73-ad49-f68a448d655f.jpeg)

**Comment by omerll** [comment]
![WhatsApp Image 2021-12-16 at 10 16 44](https://user-images.githubusercontent.com/84348234/146408941-2cc208b2-45c3-42ef-8eba-5fea93e6ed33.jpeg)

**Comment by siddiqss** [comment]
WIP

**Comment by siddiqss** [comment]
Hot water tank was completed successfully. 
Normal plastic water tank drops in temperature 21 degrees Celsius in 15 hours.
Custom built hot water tank drops temperature 5 degrees C in 15 hours.

We lose temperature 3.6 times slower compared to normal plastic tank.
The system is 3.6 times more efficient with double the price.

**Comment by omerll** [comment]
Here you see a graph of Temperature (Celsius) vs time ( hours)     The red one is the new hot water tank and the blue one is the normal plastic tank
![signal-2021-12-17-102327](https://user-images.githubusercontent.com/84348234/147365550-f826b595-24c2-4adf-931d-263c3bc2251f.jpeg)

**Comment by omerll** [comment]
Hot water tank installed on shower 
![signal-2021-12-16-164125_001](https://user-images.githubusercontent.com/84348234/147365665-5d47f4cc-96a3-422e-98f1-c6fd78bf29df.jpeg)
![signal-2021-12-16-172514_001](https://user-images.githubusercontent.com/84348234/147365668-42fd7f42-74d2-47da-8ff0-4de40d315195.jpeg)
