### ISSUE TITLE
Build Automatic Electronic system for Ininerator system

### ISSUE THREAD

**Issue by omerll** [oceanbuilders/smartpod#116]
Build incinerator prototype and all electronics and sensor

**Comment by siddiqss** [comment]
The incinerator prototype was manufactured successfully on 316L stainless steel and transported into the shop
The electronics and sensors were mounted on the incinerator prototype.

Actually making test on the burning cycles and still making progress with PLC programming.

**Comment by omerll** [comment]
![demo4](https://user-images.githubusercontent.com/84348234/147366049-ccf45624-7b26-4367-89d0-b5d6102bc984.jpg)
![demo3](https://user-images.githubusercontent.com/84348234/147366053-a6d5275f-ba4e-4f09-8dc4-0e5649bd1844.jpg)

**Comment by omerll** [comment]
Electronic Box for propotional valve
![demo1](https://user-images.githubusercontent.com/84348234/147366100-00d34a1f-407a-4a55-9e31-77e094346161.jpg)

**Comment by omerll** [comment]
Incinerator working great wih electronic design (Long test) https://drive.google.com/file/d/1Ptq2y_Js6eFnMD8VdpXUIEtIy7sHoKSK/view?usp=sharing
Short Test burning poop:
https://drive.google.com/file/d/1D9FLHr9E6XiLOSCc9LbiOdnuG7TzKbWp/view?usp=sharing
