### ISSUE TITLE
Kitchen sink and manual controls

### ISSUE THREAD

**Issue by siddiqss** [oceanbuilders/smartpod#120]
Select the water nozzle with a flexible faucet. 

Should be made of stainless steel. Should have temperature control and pressure control.

To turn ON or OFF the device will be done by capacitive touch on the metal faucet.

Should have two nozzle presets.

**Comment by amitpujar** [comment]
WIP - Omer to update on the development.

**Comment by omerll** [comment]
Temperature electronic Knob was implemented with a rotatory encoder with bearings and IP66 certified
Turning Knob was designed and 3D printed 
Pressure selection with capacitive touch was implemented 

Will show it on demo 3 Feb

**Comment by omerll** [comment]
Kitchen manual controls completed, on/ off and pressure regulation with capacitive touch. Manual Temperature regulation with smart endless knob
