### ISSUE TITLE
DESIGN: Write front end for Admin UI

### ISSUE THREAD

**Issue by scottdear** [oceanbuilders/smartpod#13]
Need to write base HTML/Javascript for Admin UI that talks to back-end defined in #12

**Comment by scottdear** [comment]
Write design document for Admin UI.   Use screenshots and from previous design.

Acceptance Critera
----------------------
Need to spec the following:
1. Front end framework - e.g. Vue, React, or Platform X.
2. Front end screen definition / functionality using screenshots from previous design work.

*NOTE* This will be running behind an Apache reverse proxy server and DynamoDB.

JS APP -> Apache Proxy -> (Service (ECS) - NodeJS/Python Flask/Django)

This will be the JS App that will call the back end services.

**Comment by olagalal** [comment]
You can check the design doc here: https://docs.google.com/document/d/1MDSWaIXL6yFZZNQQc1fad4aSIGutDWeSILnmNauuvJk/edit?usp=sharing

**Comment by olagalal** [comment]
@scottdear @angiedear I finished the doc. Review it please.
