### ISSUE TITLE
Based on Smartpod blueprint put together spreadsheet w/ lights/controller/wire order.

### ISSUE THREAD

**Issue by scottdear** [oceanbuilders/smartpod#14]
Acceptance Criteria

1. Evaluate blueprints determine, power, wiring, fuses/breakers, etc. needed for pods.
2. Get part#'s for controllers and lights strips and put in spreadsheets
3. Include wire guage and lengths, fuse/breaker amps, types and part #'s

Acceptance Criteria
-----------------------
Google Sheet  needed w/ the following, with MFG part #'s (If no part numbers then URL) and OB #'s SSC numbering from @angiedear with the following off the shelf components for each room:
1. light strips and length. and type.
2. controllers
3. diffusers
4. head dissapator's
5. cabling
6. wiring
7. switches

**Comment by godslave05** [comment]
Blockers :
1. Need to get blue print from  Sayeed
2. Also need correct blue print for the walkway
3. Need to assign issue for AC breaker panel master block to derive the AC power to rooms 
4. Need all the measuring distance among the rooms and master engineering room.

**Comment by scottdear** [comment]
We are still waiting for blueprints.  @grantromundt will need to get these for us before we can finish the Kitchen.

**Comment by grantromundt** [comment]
I haven't forgotten. I'm waiting on our engineer who is slightly backlogged
on this

Cheers,

[image: photo]
Grant Romundt
CEO, Ocean Builders
O  702-325-8092   <702-325-8092>M  415-692-1428  <415-692-1428>E
grant@OceanBuilders.com  <grant@OceanBuilders.com> W  OceanBuilders.com
<http://oceanbuilders.com/>

<http://www.facebook.com/cosmetology.education.scissorboy/>
<http://twitter.com/thescissorboy> <http://www.linkedin.com/in/scissorboy>

**Comment by omerll** [comment]
Its ready, i have taken the mesurments from the STEP file that Grant sent me 

Link to the COMPLETE Spreadsheet: https://docs.google.com/spreadsheets/d/1f4pFEqiB4IapYkTZSihGNYMfYIOEMk4sbcDRIX1jSVs/edit?usp=sharing
