### ISSUE TITLE
Master Bedroom Hardware

### ISSUE THREAD

**Issue by omerll** [oceanbuilders/smartpod#16]
Integrate the following sensors and actuators into the system, and make them accesible through home assistant:
![image](https://user-images.githubusercontent.com/84348234/118564018-2f523b00-b735-11eb-9e22-39af071f6f40.png)

**Comment by omerll** [comment]
Master Bedroom : https://docs.google.com/spreadsheets/d/1PjYPFG2qxtdeo9xYyMkP2MvSKDj4oVt-jCHFZ5IfXPs/edit?usp=sharing

**Comment by angiedear** [comment]
ongoing, waiting for parts to arrive.

**Comment by omerll** [comment]
50 % done

**Comment by Aciescognito** [comment]
Hello, this is Riley from the meeting on Monday, and based on what I can see you planning on designing some if not all of the IoT devices in house as opposed to using devices that are already on the market. I was wondering if you had a list of all the devices that you currently plan on integrating into the Seapod, and if you have already completed the technical designs for these devices. Also if Angela or Scott could contact me that would be great, I have a few questions. My email is available on my Github profile.

**Comment by godslave05** [comment]
please do a tar/cvf with the green stuffs and send them to @scottdear

**Comment by omerll** [comment]
https://github.com/oceanbuilders/Seapod-HA-V1 
Here is the repo with all my HA config
