### ISSUE TITLE
Create Spreadsheet with 1.0 Device List and Status

### ISSUE THREAD

**Issue by angiedear** [oceanbuilders/smartpod#17]
Devices needed for demo that Grant is doing on June 5th and include order status, and received by Omer and received in Panama

**Comment by omerll** [comment]
Home Asiistant integrations https://docs.google.com/spreadsheets/d/1H1-kvIouaVh4h3KLhNd_vQRyOF0eIuUo3jtIGRVKX2E/edit?usp=sharing
