### ISSUE TITLE
Create design doc for Pi Control Server

### ISSUE THREAD

**Issue by scottdear** [oceanbuilders/smartpod#2]
1. Come up with better name than Pi Control Server
2. Put together a 1-2 page high level design that defines a component API, based on the current MQTT use cases that abstracts the bus and protocol so that other bus types, e.g. CAN, NMEA can be added.
3. An OpenAPI 3.0 specification to wrap around the API's of #2 above and make the internal API's available to remote callers.
4. Must include a multi-process strategy that allows streaming of telemetry data.

**Comment by diegopau** [comment]
@siddiqss if we can close it, please close it
