### ISSUE TITLE
DESIGN: Write design for back end service to service up pod lists and establish connections.

### ISSUE THREAD

**Issue by scottdear** [oceanbuilders/smartpod#21]
1. Need to decide on NodeJS/Python/Go
2. Needs to support multiple pods, onboarding of users, and authorization, e.g. readers vs. writers/admin.
3. Need to integrate w/ SSO.

**Comment by scottdear** [comment]
@scottdear and @olagalal will discuss feasibility of serverless vs serverful approach.  @scottdear will make basic draw.io diagram for discussion.

**Comment by olagalal** [comment]
@scottdear needs to add diagrams.

**Comment by olagalal** [comment]
@scottdear any updates about the diagrams?

**Comment by olagalal** [comment]
@scottdear any updates about the diagrams?

**Comment by scottdear** [comment]
Let me know if this one makes sense:

https://github.com/oceanbuilders/smartpod/blob/main/remote_access.drawio

Quoting Ola Galal ***@***.***>:

**Comment by olagalal** [comment]
You can check the progress here:
https://docs.google.com/document/d/1PcjlqMTXRr1cYu-H9bS_d1metAvZthLJJl51ZVmGm_4

**Comment by scottdear** [comment]
We need to add more detail to the design doc, most notably we should define the endpoints needed for the different functions, e.g. list pods, add pod, etc.  Also you don't need to reference identity pools and you could copy/paste the draw.io diagram as a png, into your doc if you like.  Let me know if you have any questions.  Next step will be to create our openapi.yml file which can be used in AWS cloudformation to automagically create all of our endpoints, using the "Body" section to create our endpoints.

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-restapi.html

**Comment by olagalal** [comment]
@scottdear we already done the openapi.yml, this could work on AWS?
https://oceanbuilders.herokuapp.com/v1/docs/?urls.primaryName=Admin%20Panel%20APIs

and we define those endpoints in another doc. 
https://docs.google.com/document/d/1MDSWaIXL6yFZZNQQc1fad4aSIGutDWeSILnmNauuvJk

I added the diagram as png.

**Comment by scottdear** [comment]
hehe, this is exactly why we gotta start putting all this doc in one place.   All the links should suffice for completing the design.

I created https://github.com/oceanbuilders/ob-iac/issues/25 to take the design and the docs you linked here and implement the endpoints and lambdas.
