### ISSUE TITLE
Design and Budget Self Sufficient Solar Power System for the Pod

### ISSUE THREAD

**Issue by omerll** [oceanbuilders/smartpod#22]

**Comment by omerll** [comment]
Self Suficient Solar Power system Diagram and Budget: https://docs.google.com/spreadsheets/d/1udYdubRah645wy4YuR1tjNgF7-Mxjtg2GDWdSdj-9pQ/edit?usp=sharing

**Comment by scottdear** [comment]
Need to be reviewed by @grantromundt and Rudy
