### ISSUE TITLE
Design, Budget and Build Main Brain Computer

### ISSUE THREAD

**Issue by omerll** [oceanbuilders/smartpod#23]
Design, Budget and Build Main Brain Computer for the Pod.

Acceptance Citerea:
Light show with Adressable LEDS
Fans with Adressable LEDS
Liquid Cooling System
Speed control of Fans and Pump
Power on/off button
Good thermal stability
Crystal Case for showing whats inside 
Usb Ports 
Ethernet Port
Low power consumtion less than 90 W

**Comment by omerll** [comment]
https://user-images.githubusercontent.com/84348234/121422097-78f90480-c934-11eb-91e7-7579e401c466.MOV


https://user-images.githubusercontent.com/84348234/121422190-93cb7900-c934-11eb-8508-eab5f73ee523.MOV

**Comment by omerll** [comment]
The build includes the following  : 

- High performance/ compact  chasis with 2 tempered glass panels  for show casing, Low noise High cooling performance (color Matte White)

- 2 140 mm Aer RGB Fans addressable/Light show (Front part)

- Controller for 2 rgb led strip channels and 3 rgb fans   

 - 2 addressable Led strips hue ARBG(Light show)

- Water cooling pump 3000 rpm Magnetic Drive 5W only 

- cylindrical coolant tank 

- Aluminum cooling blocks for CPU 

- White 120mm water radiator 

- 1 Aer RBG 120 mm fan for radiator 

- 4 conectors for coolant pipes 

- Silicone Tubing 9 mm ID crystal clear 

- Blue coolant Fluid 

- 300 W  SFX  Power supply ( the system will use less aprox 55 W ) but we have room for connecting more stuff. (Is the smaller model that they sell ) 


- Conectors/Wiring/Soldering 

- Zwave certified antenna 

- Zigbee antenna 

- Raspberry Pi 

-(OPTIONAL)We can install an external HDD of 2 -4 TB for saving movies, music, photos, etc so you can play them in your pod always without internet

-and more

**Comment by scottdear** [comment]
Will bring this unit with on July 15th, will make image available on S3 so staff in Panama can burn a microSD and install in pi there with Balena Etcher. This is dependent on https://github.com/oceanbuilders/ob-iac/issues/21

**Comment by scottdear** [comment]
@omerll will send image to @scottdear and Scott will upload to S3 and finish configuration.

**Comment by omerll** [comment]
Power Draw Test: 

https://user-images.githubusercontent.com/84348234/122078728-6a8e6b00-cdc2-11eb-8597-9844c3b4cfa0.MOV

**Comment by omerll** [comment]
SeaPod Home Automation Hardware Design v2:
![SeaPod Home Automation Hardware Design v2 (2)_page-0001](https://user-images.githubusercontent.com/84348234/122772631-30631480-d26d-11eb-845f-2b2d141be1a4.jpg)

**Comment by omerll** [comment]
Waiting for Hardware 95 % completed

Modify this Diagram : https://docs.google.com/drawings/d/1up9x_ZqHC28J5Gjb-jVREDVO2UU9qGjJYzw7wdWRyLA/edit?usp=sharing

Check draw.io
