### ISSUE TITLE
Create a list pods endpoint

### ISSUE THREAD

**Issue by scottdear** [oceanbuilders/smartpod#28]
Create a GET Method endpoint that will return JSON per the already created OpenAPI spec.

1. Create a Dynamo DB table in AWS for pods.  (Read up on Single table design). via console
2. Set up API gateway.
3. Write a Lambda to read DynamoDB table and return list.  Will use boto3.

**Comment by godslave05** [comment]
Basic steps are done
Could check this API URI to get list of seapods
https://1dapkbtgnc.execute-api.us-east-1.amazonaws.com/seapods
