### ISSUE TITLE
3D Model all the components for the master bedroom/bathroom

### ISSUE THREAD

**Issue by omerll** [oceanbuilders/smartpod#30]
Design in SolidWorks(CAD Software) each electrical component that will be mounted on master bedroom :
- QI Charger
- Tablet/Touchscreen
- Set of JBL Speakers
- Projector
- Motorized screen projector
- Multisensor
- Smoke and CO sensor
- Sound Bar 
- SubWoofer
- LED PSU
- LED Controller
- Sample of LED Strip

Send it to Alessio Dragoni in STEP format, so he can fit them into the model.

**Comment by omerll** [comment]
JBL  In Celling Speakers:

https://user-images.githubusercontent.com/84348234/123680571-7b9d9a00-d80e-11eb-8e4e-94fc8dda2af5.mp4

sent to alessio_dragoni@yahoo.it in STEP format.

**Comment by omerll** [comment]
10.4 inch Tablet/ Wall Mount

https://user-images.githubusercontent.com/84348234/121422926-561b2000-c935-11eb-8e93-7bb4dd8cd5e8.MP4
 
sent to alessio_dragoni@yahoo.it in STEP format.

**Comment by omerll** [comment]
QI Charger 


https://user-images.githubusercontent.com/84348234/123682623-d33d0500-d810-11eb-83d6-fa877263440d.mp4

sent to alessio_dragoni@yahoo.it in STEP format.

**Comment by omerll** [comment]
100 inch Projector Screen

https://user-images.githubusercontent.com/84348234/123730855-aadaf800-d85c-11eb-97a7-51fb187e8cf0.mp4



sent to alessio_dragoni@yahoo.it in STEP format.

**Comment by omerll** [comment]
10 inch Subwoofer


https://user-images.githubusercontent.com/84348234/123746735-ab34bc80-d877-11eb-96b0-fcae8ea678a2.mp4

sent to alessio_dragoni@yahoo.it in STEP format.

**Comment by olagalal** [comment]
50% done

**Comment by omerll** [comment]
Full HD 16:9 100 inch Projector Screen (New version that we will use) the last one i sent was 4:3 aspect ratio


https://user-images.githubusercontent.com/84348234/123846311-d13f7880-d8da-11eb-966a-e8a1ca8b290c.mp4



Sent to alessio_dragoni@yahoo.it in STEP format.

**Comment by omerll** [comment]
Power Supply for LED Strips 48 v 5A Fanless design MeanWell IP67 (5 year warranty)


https://user-images.githubusercontent.com/84348234/124052061-4bf3bb00-d9e3-11eb-8ae0-da11ff98c462.mp4



Sent to alessio_dragoni@yahoo.it in STEP format.

**Comment by omerll** [comment]
MultiSensor (Temperature, Humidity, Lux, Motion, UV Light)


https://user-images.githubusercontent.com/84348234/124061450-7a2dc680-d9f4-11eb-914f-226548606547.mp4


Sent to alessio_dragoni@yahoo.it in STEP format.

**Comment by scottdear** [comment]
80% done on defining components and will handoff to alessio_dragoni@yahoo.it

**Comment by omerll** [comment]
ROKU Streambar 4K / HD / HDR Streaming Device and Premium Audio(Dolby Audio Certified), All in One 4 speakers

https://user-images.githubusercontent.com/84348234/124321971-36e26d80-db44-11eb-8f2f-e00c19789de3.mp4

Sent to alessio_dragoni@yahoo.it in STEP format.

**Comment by omerll** [comment]
LED Strip Controller 48V RGBWW 


https://user-images.githubusercontent.com/84348234/124363002-46be8800-dbfe-11eb-8fe6-5d261e182592.mp4

Sent to alessio_dragoni@yahoo.it in STEP format.

**Comment by omerll** [comment]
LED Strip 48V RGBWW


https://user-images.githubusercontent.com/84348234/124844927-34747f00-df5b-11eb-8a87-5730c6585062.mp4

Sent to alessio_dragoni@yahoo.it in STEP format.

**Comment by omerll** [comment]
Smoke and CO Sensor 


https://user-images.githubusercontent.com/84348234/124941457-6b38ac80-dfd0-11eb-9241-f16635dfcff9.mp4


Sent to alessio_dragoni@yahoo.it in STEP format.

**Comment by omerll** [comment]
RF 315Mhz Transmitter(Controls the proyector screen)


https://user-images.githubusercontent.com/84348234/124941766-aa66fd80-dfd0-11eb-8522-f158e2007608.mp4

Sent to alessio_dragoni@yahoo.it in STEP format.
