### ISSUE TITLE
Create a POST endpoint for adding a POD 

### ISSUE THREAD

**Issue by scottdear** [oceanbuilders/smartpod#35]
Add this to the rest API created in #28 and add a new lambda to to an Add pod.

**Comment by scottdear** [comment]
3 points

**Comment by omerll** [comment]
Scott need to update permitions for cloudwatch for Asad

**Comment by godslave05** [comment]
@olagalal 
POST: 
https://yb4lptrfk9.execute-api.us-east-1.amazonaws.com/dev

REQUEST FORMAT:
{
    "id":"7",
    "name":"seapodSeven",
    "port":"1001"
}

**Comment by angiedear** [comment]
2 points

**Comment by omerll** [comment]
Issue is solved wait for review
