### ISSUE TITLE
Projector Screen Control HA-server/ make integration for 315Mhz Transmitter 

### ISSUE THREAD

**Issue by omerll** [oceanbuilders/smartpod#36]
1.- Sniff Codes from projector screen remote. 

2.- Copy them to the HA-server 

3.- Make integration for 315Mhz Transmitter to send commands and control screen via the app. 

4.- Calculate the ideal lenght for the 315Mhz antenna

5.- 3D design and print  a case for the transmitter(TX)

6.- Build ,Test, and connect the device

**Comment by omerll** [comment]
1.-
        Turn Down projector screen: 10897748 / 24 bits/ Protocol: 1
        Turn Up projector screen: 10897746 /  24 bits/ Protocol: 1
         STOP projector screen: 10897752 / 24 bits/ Protocol: 1
Sniffed codes from remote with custom 315Mhz sniffer

**Comment by omerll** [comment]
2.- Commands copied to HA

switch:
  - platform: rpi_rf
    gpio: 4
    switches:
      projector_screen:
        code_on: 10897748
        code_off: 10897746

**Comment by omerll** [comment]
4.- Calculate the ideal lenght for the 315Mhz antenna

![antenna315](https://user-images.githubusercontent.com/84348234/125316185-7e63b900-e2fd-11eb-8b98-648def12cb4d.jpg)

**Comment by omerll** [comment]
5.- 3D design and print a case for the transmitter(TX)

3D Design:
https://user-images.githubusercontent.com/84348234/125316388-b408a200-e2fd-11eb-9869-cbb67a7c7117.mp4

3D Print finished product photos:
![ss1](https://user-images.githubusercontent.com/84348234/125317048-4f017c00-e2fe-11eb-9683-3a8b93ea44ad.jpg)
![ss2](https://user-images.githubusercontent.com/84348234/125322193-1c0db700-e303-11eb-849e-f01093306459.jpg)

**Comment by omerll** [comment]
6.- Demo  1 and final product 

https://user-images.githubusercontent.com/84348234/125322608-93dbe180-e303-11eb-9e4b-b8a6d56698fb.mp4


Demo 2:
https://user-images.githubusercontent.com/84348234/125322653-9f2f0d00-e303-11eb-94a0-8c7981663514.mp4

**Comment by scottdear** [comment]
Can we move the documentation for this store into a github repository along with the source code?

**Comment by omerll** [comment]
Yes
