### ISSUE TITLE
Combustible Gas sensor 

### ISSUE THREAD

**Issue by omerll** [oceanbuilders/smartpod#37]
1.- Make integration for Combustible Gas sensor.,Read the values and send them to the UI

2.- Make automation to send push notification if gas is detected

**Comment by omerll** [comment]
1.- Integration made and config process
1.1.- UI updated 
Check: https://github.com/oceanbuilders/Seapod-HA-V1/blob/main/lovelaceui.yaml
From line 183 to 186

2.- Automation written 
Check :https://github.com/oceanbuilders/Seapod-HA-V1/blob/main/automations.yaml
from line 88 to line 112

**Comment by omerll** [comment]
Demo on the Combustible Gas sensor:

https://user-images.githubusercontent.com/84348234/125350975-1e810880-e325-11eb-89a1-e09fe88708c2.mp4

**Comment by omerll** [comment]
Push notification recived on my phone, also grant confirmed recived as well:
![noti](https://user-images.githubusercontent.com/84348234/125351240-791a6480-e325-11eb-8f8b-a83617a2acfb.jpg)

**Comment by scottdear** [comment]
Can we get any source code checked in, a pull request for at least a README file?  Also we need notes on what is left to be done to do an actual HASS integration that we can click on from the integrations and/or add-ons.

**Comment by scottdear** [comment]
Also it would be helpful to have instructions on how to install these files if there is no actual integration or add-on.  The process should be as follows:
1. Create a branch for your changes
2. Do changes and commit
3. Push changes to github
4. Create a pull request for the changes in github
5. Move the issue to review and request a code review
6. Code is reviewed by qualified member on team
7. Code is merged/deployed.

For each of these issues we need to follow the above process and it needs to be checked into smartpod, hass-integration or hass-add-ons repository.

**Comment by omerll** [comment]
We will open a new issue for this. Design and test completed
