### ISSUE TITLE
create a lights python module

### ISSUE THREAD

**Issue by scottdear** [oceanbuilders/smartpod#4]
Needs to support the following api calls:

listLights() lists lights on network
getLight() gets detailed information on a particular light
setLight() sets attributes of a light, e.g. on, off, intensity

This should be a proper python module that has unit tests, e.g. unittest or pytest

**Comment by angiedear** [comment]
L T-Shirt

**Comment by angiedear** [comment]
@scottdear where are we at with this issue?  Update status please.

**Comment by scottdear** [comment]
@angiedear I spoke w/ Dorian to see if he wanted to take this one on.  I'm awaiting a response.

**Comment by diegopau** [comment]
@omerll if we can close this, please close it

**Comment by omerll** [comment]
This is deprecated, no longer valid, architecture of seapod hardware changed!
