### ISSUE TITLE
Integrate Voltage and Current Sensors for the Turbine Instrumentation System

### ISSUE THREAD

**Issue by omerll** [oceanbuilders/smartpod#41]
Integrate the high voltage sensors w/ AT Mega MCU for turbine instrumentation.

Acceptance Criteria
---------------------
1. Hand off a Rasberry Pi w/out Home Assistant integration to Jermiah that talks to the AT Mega MCU for the Turbine Instrumentation System.
2. Check in Source code w/ MCU Source, and any Draw.io diagrams and README w/ how to reproduce setup in 1.

**Comment by scottdear** [comment]
Estimated 3 points

**Comment by omerll** [comment]
Current sensor integrated, 50 % done
