### ISSUE TITLE
Create User Flow Diagram for Admin UI

### ISSUE THREAD

**Issue by olagalal** [oceanbuilders/smartpod#42]
Acceptance Criteria:
--------------------
Should provide user flow for (Admin Scenario):
- Registration
- Login
- Forget Password
- Logout
- View Seapods (Table and Map Views)
- Get Specific Seapod Info

**Comment by omerll** [comment]
In progress =)

**Comment by angiedear** [comment]
3 points

**Comment by angiedear** [comment]
In progress no blockers

**Comment by angiedear** [comment]
In progress

**Comment by omerll** [comment]
In progress no blockers

2 points left???

**Comment by olagalal** [comment]
> In progress no blockers
> 
> 2 points left???

Yes

**Comment by godslave05** [comment]
In progress. 
[1 point]

**Comment by angiedear** [comment]
Reviewed, looks great!  @olagalal we can close this issue and use it for reference when needed.
