### ISSUE TITLE
Design, Build and Budget water level monitor for water tanks

### ISSUE THREAD

**Issue by omerll** [oceanbuilders/smartpod#43]
1.- Make system to monitor water level from 0 to 100 % in :

Hot water tank
Cold water tank
Salt Water tank
Drinkable Water tank

2.- Write integration to Home assistant

**Comment by angiedear** [comment]
@omerll should we be breaking this issue down into smaller stories?

**Comment by omerll** [comment]
Yes is super important ! we need to build it

**Comment by siddiqss** [comment]
A differential pressure sensor MPXV4006DP was selected and implemented with our POE microcontroller.
A stainless steel 3mm tube was ordered. Calibration of sensor is pending until these arrive. Integration with HA is done.

**Comment by omerll** [comment]
System is done, and working correctly you will see it on the 6 of Jan demo !
