### ISSUE TITLE
Design, Budget and Build Salt water tank pump controller

### ISSUE THREAD

**Issue by omerll** [oceanbuilders/smartpod#44]
1.- The device needs to full the salt water tank all the time via a salt water pump 

2.- Write integration for home assistant

**Comment by angiedear** [comment]
@omerll is this issue still relevant?

**Comment by omerll** [comment]
Yes is super important ! we need to build it

**Comment by siddiqss** [comment]
The water level sensor, the pump, the microcontroller, the watertank was ordered and delivered.
3D design was done. 3D printing and assembly is still pending.

**Comment by omerll** [comment]
3D Case done

![signal-2022-01-26-085050](https://user-images.githubusercontent.com/84348234/151399426-c9d28886-7f69-4a7c-b75e-df5575aac76a.jpeg)

**Comment by amitpujar** [comment]
WIP - Programing and integration pending.

**Comment by omerll** [comment]
Salt Water tank  was completed and working correctly will make make futther testing, and probably will show it on demo 3 of Feb

**Comment by omerll** [comment]
Testing was done, device is working as expected and filing all the requirments.
will show it on demo 3 of Feb
