### ISSUE TITLE
Design, Budget and Build 110/12v/5v charge station 

### ISSUE THREAD

**Issue by omerll** [oceanbuilders/smartpod#45]
Build a small foot print charge station with the following outlets:

-  2 IP65 110v Outlet 10 Amps max
- 1 IP65 12v outlet cylindrical connection  
- 2 IP65  5V USB C or USB 2.0

**Comment by omerll** [comment]
Hardware arrrived, 3D modeling in progress

**Comment by omerll** [comment]
Include IP65 Ethernet port, enables to connect your laptop, pc or other hardware by wire and disable the wifi connections

**Comment by omerll** [comment]
Charging Station V1 3D design:
https://user-images.githubusercontent.com/84348234/126578812-3e3babec-40b6-4946-b47a-5cec818d1bf1.mp4

**Comment by omerll** [comment]
Charging Station V1 prototype model:
https://user-images.githubusercontent.com/84348234/126579057-14c7f94b-3f15-4694-b985-10265760c0f1.mp4

**Comment by omerll** [comment]
Grant: 
- 3d model SeaDapter model and include it to the Charging Station.(https://www.switchcraft.com/Documents/Switchcraft_High_Amperage_Power_Jacks_&_Plugs_NPB_599.pdf)
- Change the 2 USB 3.0 port for 1 USB C and 1 USB 3.0 sockets.

**Comment by omerll** [comment]
Grant:
- SeaDapter model gets canceled  for now maybe we will included in the future. We will use the 12V socket Marine that was included on the design (https://user-images.githubusercontent.com/84348234/126579057-14c7f94b-3f15-4694-b985-10265760c0f1.mp4)

**Comment by omerll** [comment]
Charge Station Completed 100%:
![image](https://user-images.githubusercontent.com/84348234/127012942-e02bccc8-89d8-4788-9eab-79d2e6aba8a4.png)

**Comment by scottdear** [comment]
Check 3dmodels and other relevant files into smartpod repo.

**Comment by omerll** [comment]
Files uploaded
