### ISSUE TITLE
Design, Budget, Build Shower system 

### ISSUE THREAD

**Issue by omerll** [oceanbuilders/smartpod#48]
1. Should be able to turn on shower by voice, app, swiping your NFC ring in front of reader. App should store your preferred shower temperature and adjust the temperature to that automatically for you.
2. Should be able to adjust the temperature of shower by voice (asking for a specific temperature or to turn temp up or down by X degrees or percent?!?). Also adjust by app.
3. Manual controls? Is there any way to have a manual faucet handle to control the temp in additional to digital control?
4. OR should we have a waterproof tablet in the shower to control the shower?
5. We need to have a pump to get water to the shower from the storage room and have a nice steady flow and pressure. Maybe the same pump can also supply the bathroom sink faucet
6. Can the system control the hot/cold water so the user gets their preferred water temp?

**Comment by scottdear** [comment]
8

**Comment by angiedear** [comment]
@omerll should this be broken down into smaller stories?

**Comment by omerll** [comment]
Yes can be broken into multiple stories.... is a 10 point story aprox
