### ISSUE TITLE
Solder, Build and Test 48 V RBGWW LED 15 m Strips

### ISSUE THREAD

**Issue by omerll** [oceanbuilders/smartpod#50]
1.- Solder the LED Strips each 5 m to create a 15m Strip(The system could have up to 30 m Strips) and make connections between the controller and the LED Strip

2.- Test the LED strips with the code written by @omerll in the past for LED Strips, and also make test on thermal estability

3.- Make a quick demo showing diferent colors of light, Cold White and Warm White for stakeholders.

**Comment by omerll** [comment]
1.- Solder joint: 
![photo_2021-07-12_23-22-34](https://user-images.githubusercontent.com/84348234/125390572-b7854300-e368-11eb-98d0-6c3adaed3f3a.jpg)


Solderless joint: 
![photo_2021-07-12_23-22-22](https://user-images.githubusercontent.com/84348234/125390574-b81dd980-e368-11eb-8594-9aa5c7ef0157.jpg)




The LED Strip was created sucessfully

**Comment by omerll** [comment]
2.-
- Test was done sucessfully the light intensity is the same on the start of the strip until the end of the strip(Measured with luxmeter)

- Temperature is stable at 40 degres C after 5 hours of emmiting light at full Load

- Code works as expected, we can select from big range of colors and also switch to cold white or warm white light color temperature.

**Comment by omerll** [comment]
3.- LED system for master bedroom done and working perfect:
https://user-images.githubusercontent.com/84348234/125391508-3fb81800-e36a-11eb-9b91-431f20279671.MOV

**Comment by scottdear** [comment]
For these issues, we really do not need videos, what we need is source code, or at a minimum we need a README.txt placeholder that mentions what is still needed.  Please include any dependencies and build/installation instructions.
