### ISSUE TITLE
Write MCU code to control turbine and talk to Raspberry Pi

### ISSUE THREAD

**Issue by scottdear** [oceanbuilders/smartpod#51]
Acceptance Criteria
-----------------------
Code for MCU to talk to Turbine Instrumentation System and Raspberry Pi

This will be used in addition to the Turbine System (R&D project).

**Comment by omerll** [comment]
This is deprecated, no longer valid, architecture of seapod hardware changed!
Tesla Turbine already has is own instrumentation system that resports to HA if necesarry!
