### ISSUE TITLE
Electrical System-List of Loads

### ISSUE THREAD

**Issue by angiedear** [oceanbuilders/smartpod#55]
Make complete lists of loads and consumption time of each load.  
2 pts

**Comment by omerll** [comment]
List of lods and analysis done: https://docs.google.com/spreadsheets/d/1Z3EUDIzAI0BPieWTWOwFb1E0aJhBOSGRjH5RA7O6th8/edit?usp=sharing

**Comment by scottdear** [comment]
@omerll will work w/ @diegopau go get this in the right place in the wiki.

**Comment by omerll** [comment]
File uploded to OceanBuilders google drive file sharing service(agreed by diego and grant), files update automatically when i edit any of them, this way we always have the most updated version available. All files in XLSX format
