### ISSUE TITLE
Power System- Redesign Solar Generation and Storage System

### ISSUE THREAD

**Issue by angiedear** [oceanbuilders/smartpod#56]
Redesign with new specifications given by Grant.

**Comment by omerll** [comment]
3 new different budgets uploaded to: https://docs.google.com/spreadsheets/d/1hMk-XVZAbfccNeqQDVlqqQjmy3Xp31wsa3zvu3uP7L0/edit?usp=sharing

Notice that the Spreadsheet has multiple pages, there you will find the 3 new budgets, and a comparison between the 3 budgets, Net present value analysis was made to have more info to take the right decision

**Comment by scottdear** [comment]
Export spreadsheet to xlsx and upload the OB file sharing service.

**Comment by omerll** [comment]
File uploded to OceanBuilders google drive file sharing service(agreed by diego and grant), files update automatically when i edit any of them, this way we always have the most updated version available. All files in XLSX format
