### ISSUE TITLE
Electrical System- Main Electrical Diagram and Calculations

### ISSUE THREAD

**Issue by angiedear** [oceanbuilders/smartpod#58]
Acceptance criteria:

1.  Complete electrical diagram including cable gage, grounds, circuit breakers, busbars, main electrical panels
2. Spreadsheet with all the calculations for each AC circuit and DC circuit

5-6 points

**Comment by angiedear** [comment]
In progress no blockers

**Comment by omerll** [comment]
Calculations and Diagrams uploded to Ocean Builders GSuite

@grantromundt 
@diegopau 
Amit

**Comment by omerll** [comment]
Files available in : https://drive.google.com/drive/folders/1QWxdqsLMDGxP_hk9tMSqbHLGonyrnZ8v?usp=sharing

**Comment by grantromundt** [comment]
thanks Omer!

Cheers,

[image: photo]
Grant Romundt
CEO, Ocean Builders
O  702-325-8092   <702-325-8092>M  415-692-1428  <415-692-1428>E
***@***.***  ***@***.***> W  OceanBuilders.com
<http://oceanbuilders.com/>

<http://www.facebook.com/cosmetology.education.scissorboy/>
<http://twitter.com/thescissorboy> <http://www.linkedin.com/in/scissorboy>

**Comment by diegopau** [comment]
Relevant documents uploaded to http://files.oceanbuilders.com/smart-link/402207a0-a8a2-4c39-8bf6-ab3eda30a752/
