### ISSUE TITLE
Integrate mockup w/ new lights module

### ISSUE THREAD

**Issue by scottdear** [oceanbuilders/smartpod#6]
When the lights module is completed in #4, create link this to the mockup created in #5 and validate the lights turn on and off when the API is called.

Acceptance criteria.
----------------------
When the REST API is called it responds to the hardware plugged in to the can bus in the raspberry pi.

**Comment by diegopau** [comment]
@omerll if we can close this, please close it

**Comment by omerll** [comment]
This is deprecated, no longer valid, architecture of seapod hardware changed!
