### ISSUE TITLE
UI for the instrumentation system

### ISSUE THREAD

**Issue by angiedear** [oceanbuilders/smartpod#63]
Acceptance Criteria

Dashboard showing all variables in real time with a refresh rate of 1000 milliseconds
Graphana dashboard that reads from MySQL database with telemetry data.

**Comment by omerll** [comment]
2 sensors are missing calibration
Need to add 
- Start/Stop Test button
- Download button for XLSX File

**Comment by angiedear** [comment]
In progress, blocked by current sensor has issues and needs to be changed for a different type, email sent to Hendrik to purchase new one, waiting on response.

**Comment by amitpujar** [comment]
Hendrik has procured the sensor. He's on track and should be ready for the demo on Tuesday.

**Comment by omerll** [comment]
All the sensors are connected to the UI, calibrated and synchronized in time 👍🏼👍🏼

https://user-images.githubusercontent.com/84348234/133812700-10a19403-5977-4236-ad62-79a7335b8c83.mp4

**Comment by omerll** [comment]
Case for the brain computer:


https://user-images.githubusercontent.com/84348234/134025497-18935fa0-bc14-480b-8084-c0d02a18c97a.mp4

**Comment by angiedear** [comment]
Demo meeting with Jeremiah, went well.  Some of the electronics need cases to finish project, seal for shipping.
