### ISSUE TITLE
Configure Redis in AWS

### ISSUE THREAD

**Issue by angiedear** [oceanbuilders/smartpod#64]
Set up cache and sessions

**Comment by angiedear** [comment]
@scottdear Is this issue a placeholder?  Do we need to add more detail and an acceptance criteria?

**Comment by angiedear** [comment]
@godslave05 is this a duplicate issue?

**Comment by godslave05** [comment]
Not totally duplicate but intertwined with #65

**Comment by diegopau** [comment]
Not relevant anymore
