### ISSUE TITLE
Integrate Magnetic Drive Door into the system

### ISSUE THREAD

**Issue by omerll** [oceanbuilders/smartpod#66]
Acceptance Criteria:
1.- The door can be opened and closed mannually by pushing and pulling the door
2.- The door can be opened and closed when reading a valid tag with the NFC reader
3.- The door can be opened and closed with tha home assistant app

2-3 points

**Comment by omerll** [comment]
1.- The door can be opened and closed mannually by pushing and pulling the door
2.- The door can be opened and closed when reading a valid tag with the NFC reader

Demo Video of this 2 fuctions working


https://user-images.githubusercontent.com/84348234/133465830-c0646e8f-088d-47e2-8998-426a83079c25.MOV

**Comment by omerll** [comment]
3.- The door can be opened and closed with tha home assistant app

Demo with home assistant app:

https://user-images.githubusercontent.com/84348234/133466175-9a9a0280-5180-4c1b-9827-5118fb8a8614.mp4

**Comment by omerll** [comment]
3D design for electronics:

https://user-images.githubusercontent.com/84348234/133466611-710580b6-69ea-4f53-8fa7-d48f95835b8c.mp4

**Comment by omerll** [comment]
3D printing in progress 9 hours left
![Capture](https://user-images.githubusercontent.com/84348234/133467389-7a853c3c-8410-48c3-afc5-e31a427de73b.PNG)

**Comment by omerll** [comment]
Door controller 🚪 printed and assembled 👍�

https://user-images.githubusercontent.com/84348234/133813299-4a2d2917-74c7-4ecb-8e11-ffaa4b998141.mp4

�

**Comment by angiedear** [comment]
Needs documentation, needs testing on actual door in future.
