### ISSUE TITLE
Design MCU Controller Node

### ISSUE THREAD

**Issue by scottdear** [oceanbuilders/smartpod#7]
Design the initial controller Node.

This will be an ESP32 ARM processor chip.  It will keep the following information regarding devices on the bus it is on and respond to requests from the Raspberry Pi.

1. A list of devices and their unique ID's
2. For each device the last 100 events (less if there are memory issues)
3. For each device it's last reported state(s)
4. For each device it's last configured state.

The controller is the state exchanger and data buffer between the CAN bus and the Raspberry Pi, so the that the Pi will only contact this node directly.  This will offload event processing to the ESP32 instead of the Pi having to spend cycles processing CAN bus events from all devices.

This controller will also container logic that will attempt to maintain states and errors that bring the last reported state to equal the last configured state.  Eg. The Pi tells the controller to turn the light on, and the controller sends the right event to the right device then awaits confirmation and updates states in it's internal buffers.  The Pi polls/selects on the controller and waits for the state light to change as desired.

Acceptance Criteria
---------------------
A design document with diagrams that describes the hardware software and firmware components needed to implement the above.

**Comment by scottdear** [comment]
https://community.home-assistant.io/t/canopen-can-bus-for-home-automation-a-good-idea-or-not/54799/23

**Comment by diegopau** [comment]
@omerll if there is no use for this anymore, please close it

**Comment by omerll** [comment]
This is deprecated, no longer valid, architecture of seapod hardware changed!
