### ISSUE TITLE
Shipping for UI system 

### ISSUE THREAD

**Issue by angiedear** [oceanbuilders/smartpod#73]
#63 Split from issue.  Ship all of sealed components to Jeremiah in Idaho.  

Acceptance Criteria:
1.  Cover all sensors with foam
2. Use double sided box to ship
3. Seal all connections and electronics,  nice look and feel.  
4. Speak with Hendrik re: reimbursement with shipping costs.

**Comment by omerll** [comment]
Brain Computer Case

https://user-images.githubusercontent.com/84348234/134048394-39aef6d2-ec62-4ad4-b6ef-3c6696e26e9a.mp4

:

**Comment by omerll** [comment]
Rpm Sensor Case 

https://user-images.githubusercontent.com/84348234/134048451-9bc1ca3a-72e2-4994-9ea0-6fe41799c074.mp4

:

**Comment by omerll** [comment]
Current Sensor Case

https://user-images.githubusercontent.com/84348234/134061611-19252178-c4d9-4ad9-a1bd-70692831d6fc.mp4

:

**Comment by omerll** [comment]
RPM Sensor Case:
https://user-images.githubusercontent.com/84348234/134068683-a60f3895-38d0-4475-9157-15c87ffa483e.mp4

**Comment by angiedear** [comment]
In progress, no blockers

**Comment by omerll** [comment]
Today we ship it.

**Comment by omerll** [comment]
Electronics finished, everthing is sealed in polymer cases 
![ws3](https://user-images.githubusercontent.com/84348234/135001739-d6d9a798-a86c-4f16-8095-ce8d974117cd.jpg)

**Comment by omerll** [comment]
All the electronics and sensors are coverd and protected with foam, packeage seal
https://user-images.githubusercontent.com/84348234/135001876-317ff28b-2e0c-40f7-9a22-7c6a41eedb7b.mp4

![ws4pa](https://user-images.githubusercontent.com/84348234/135001860-d4664434-c688-4a31-8575-53408e3383ff.jpg)

**Comment by omerll** [comment]
Shipping Receipt:

[VATReceipt_6026249342.pdf](https://github.com/oceanbuilders/smartpod/files/7240049/VATReceipt_6026249342.pdf)

**Comment by omerll** [comment]
Jeremiah confirmed that the shipping arrived =)
