### ISSUE TITLE
Create Budget and BOM for Solar System 

### ISSUE THREAD

**Issue by angiedear** [oceanbuilders/smartpod#75]
New supplier, need to give us new estimates due to closer proximity to office in Panama.
Order components as soon as possible.

**Comment by omerll** [comment]
Design was finished!
Blocked on the budget, waiting for suppliers to send quote.
Problems with semiconductors shortage

**Comment by godslave05** [comment]
Still waiting

**Comment by omerll** [comment]
New solar Budget Available in: https://docs.google.com/spreadsheets/d/1qTDBg3LI6SkqPMpnbN6HPXGAgDRBrjkdVu5k9GRwRNU/edit?usp=sharing

We need two of these systems, one on each outter spar, we can start with one and as more power is requiered we install the second system

[NewSolar Budget .xlsx](https://github.com/oceanbuilders/smartpod/files/7248882/NewSolar.Budget.xlsx)
