### ISSUE TITLE
Select Components based on Requirements

### ISSUE THREAD

**Issue by angiedear** [oceanbuilders/smartpod#76]
Sink, shower, jacuzzi etc. consult with Hendrik.  Basic components. 

1	Jacuzzi Jets	
		
1	Shower Head	
1	Hand Held	
6	Massage Shower	
		
1	Bathroom Sink with sensor	
		
1	Kitchen Sink	
1	Drinkable water system	
		
1	Desalination machine	
		
1	Water compressor	
3-4	Filters

**Comment by omerll** [comment]
The components where chosen with the help of Hendrik...

1 Jacuzzi Jets: https://www.alibaba.com/product-detail/LED-SPA-light-with-plastic-jacuzzi_60758177507.html?spm=a2700.galleryofferlist.normal_offer.d_title.785b4c82dEDDXV

1 Shower Head: https://homedec-household.en.alibaba.com/product/1600301151841-828806795/Public_bathroom_self_closing_bath_shower_set_8_inch_304_stainless_steel_square_shower_head.html?spm=a2700.shop_plgr.41413.17.61f15fdccRvu9p

1 Hand Held: https://www.alibaba.com/product-detail/16inch-Thermostatic-LED-Shower-System-set_1600273406593.html?spm=a2700.wholesale.0.0.7f4a2c6cjbHiNc

6 Massage Shower: https://www.alibaba.com/product-detail/16inch-Thermostatic-LED-Shower-System-set_1600273406593.html?spm=a2700.wholesale.0.0.7f4a2c6cjbHiNc

1 Bathroom Sink with sensor: https://homedec-household.en.alibaba.com/product/1600304246679-829078289/Cold_and_Hot_Water_Basin_Tap_Mixer_Bathroom_Touchless_Automatic_Motion_Sensor_Sink_Faucet_with_Cover_Plate.html?spm=a2700.shop_plgr.41413.13.472c193f8DLQZM

1 Kitchen Sink: https://homedec-household.en.alibaba.com/product/1600306265519-825888101/Brushed_Nickel_Automatic_Smart_Touch_Sensor_pull_out_water_mixer_tap_Kitchen_sink_Faucet_with_Pull_Down_Sprayer.html?spm=a2700.shop_plgr.41413.38.6403193fLwZCiI

1 Drinkable water system: https://articulo.mercadolibre.com.mx/MLM-666029553-equipo-purificador-osmosis-inversa-6-etapas-con-uv-mirage-_JM?searchVariation=33333870187#searchVariation=33333870187&position=6&search_layout=grid&type=item&tracking_id=e971537a-bbca-4ab6-943a-b886d0497645

1 Desalination machine: This will be custom made =), and we have a separate issue for this 
( Desalination machine/ Water compressor: Custom made with 316L stainless steel)
( Desalination machine/ Filters: https://www.freshwatersystems.com/products/filmtec-sw30-2521-sea-water-300-gpd-ro-membrane-element?variant=13249942683691&c1=GAW_SE_NW&source=PLA_USA_SS&cr2=smart_shopping__-__all_products_112768&kw=6311_13062_0&cr6=pla&cr7=c&utm_campaign=gs-2020-01-06&utm_source=google&utm_medium=smart_campaign&gclid=Cj0KCQjwka_1BRCPARIsAMlUmEoxocJvX76uESSlIM-1vzyHz6jsvwC-5UtplVq7DVpzVwbqkClKUmcaAkTEEALw_wcB)
