### ISSUE TITLE
Write bilge pump to home-assist design document

### ISSUE THREAD

**Issue by scottdear** [oceanbuilders/smartpod#8]
We want to take off the shelf 3 wire Bilge pumps and connect them to an inexpensive MCU that supports CAN bus.

This story is dependent on #7 .  It will receive commands from the Controller MCU node to do the following:
Receive Events
-----------------
1. Turn Pump On
2. Turn Pump Off
3. Report Pump Status on/off
4. Report Water Detected/Not Detected

Send Events
--------------
1. Water Detect state change detected/not detected
2. Pump Activated
3. Pump Deactivated  

Acceptance Criteria
---------------------
A two page document with diagrams that describes the hardware, software and firmware components defined in implementing bilge pumps as discrete addressable devices.

**Comment by omerll** [comment]
Pump system: https://docs.google.com/spreadsheets/d/14gFoo9_OFFapPEOC7xSg4C_GLqYjKI6hd-_5Xfo-Zhs/edit?usp=sharing

**Comment by omerll** [comment]
Demo on the integration of homeassistant with PLC that will be the controller for the bilge pump 
https://user-images.githubusercontent.com/84348234/121420564-d7bd7e80-c932-11eb-897d-6f21f4ba1370.mp4

Pump system budget and diagram: https://docs.google.com/spreadsheets/d/14gFoo9_OFFapPEOC7xSg4C_GLqYjKI6hd-_5Xfo-Zhs/edit?usp=sharing

**Comment by angiedear** [comment]
Write up one page doc explaining what the PLC does.

**Comment by olagalal** [comment]
Being made with FPGA

**Comment by omerll** [comment]
Waiting on the hardware

**Comment by omerll** [comment]
Design Document: 
[Pump System (Documentation).pdf](https://github.com/oceanbuilders/smartpod/files/6736137/Pump.System.Documentation.pdf)
https://docs.google.com/document/d/1EVJpNxRDtiEZHkuA2yFqpOtG4Sxv6HJQXhO4TkF2GDE/edit?usp=sharing

**Comment by scottdear** [comment]
@omerll I couple of things we'll want to do for the long term design.

1. We need a short term solution w/ an off the shelf marine grade bilge pump.  Based on their location we will need to spec out different sizes and include gallons per hour.   There are also off the shelf sensors that are marine grade.  We should use a pump that can be integrated into the long term solution.
2. The design needs to use CAN bus which is broadcast based, and not Ethernet which is hub and spoke and has a single point of failure. (this is for the long term solution)
3. The design needs to include the details of how the controller for the bilge pump (w/ integrated sensor) and each of the additional sensors need an MCU that will talk to the CAN bus.
4. The protocol between the sensor MCU's and the bilge pump MCU and the master MCU needs to be defined in the design document for CAN bus, e.g. When external sensor X detects water it will send message X to the bus w/ the following format in CANOpen, e.g. timestamp, etc.  We need all the details in there so we can code it up on the MCU's

*** As an overall design note, we should not be using Ethernet especially for sensors.  Ethernet has a latency that doesn't play well w/ real time telemetry.  w/ Ethernet and TCP/IP it's a message is not considered sent until the other end receives it.  If the other end goes out, then the sending ends buffers fill up until everything crashes.  w/ a broadcast based protocol, it just sends the messages.   Also if the hub/switch takes a hit, then any sensor that is not  directly connected to the single MCU/PLC that the bilge pump is connected to will not be able to tell anyone that it detects water.  We should _NOT_ be using Ethernet as a backbone, especially for mission critical systems such as CAN bus and in any design where we do use Ethernet we need to spec marine grade connectors and cables on the devices.  We can meet this week if you need more details, but we needs to make some adjustments.

Also please provide feedback in discord on github markdown checked into the Repo or Wiki for design docs.  We need to get these guys in a central place and in a standard text based format where we can track revisions and updates to design docs and requirements documents.

**Comment by scottdear** [comment]
https://www.westmarine.com/bilge-pumps

Most of the sensors I have seen involve some type of float.

Question:  If the prism is covered w say, oil or algae or other light interrupting substance, will it affect the operation of the sensor?

Also lets get this converted to Markdown and check the images in to an assets directory in the smartpod repo.

**Comment by angiedear** [comment]
@omerll is this still relevant?

**Comment by omerll** [comment]
No, no anymore

**Comment by omerll** [comment]
https://github.com/oceanbuilders/smartpod/issues/106 issue done
