### ISSUE TITLE
Build, tune and test pressure/flow controller for shower

### ISSUE THREAD

**Issue by angiedear** [oceanbuilders/smartpod#81]
Acceptance Criteria:
1.  System should be able to push water 6.4 meters in height
2. It can be controllable in 10 levels in shower.

**Comment by omerll** [comment]
Pressure sensor was ordered, and instaled with custom 3D printed adapter to the shower piping
Variable Frequency Drive needs to be ordered
Higher pressure pump need to be order for 60 L/min 
Component selection process is in progress, searching for good prices ans suppliers

**Comment by omerll** [comment]
Variable Frequency Drive was ordered from TELCO Westing House with ModBus Conmmunication L510
Higher pressure pump was ordered to produce 50 PSI and 60l/min at max speed.

Should this week arrive 18-19 of nov

**Comment by siddiqss** [comment]
The jet pump was installed and controlled successfully with our shower system via a VFD, microcontroller and communication with HA. The system achieves a maximum pressure of 20psi when the 3 outlets handheld shower, shower head and massage jets simultaneously.
