### ISSUE TITLE
Build, tune and test temperature controller for shower

### ISSUE THREAD

**Issue by angiedear** [oceanbuilders/smartpod#82]
Acceptance Criteria:
1.  System should be regulating temperature from 20 to 60 degrees C
2. Error should not be bigger than + - 1.5 degrees C

**Comment by omerll** [comment]
Temperature sensor was ordered, and instaled with custom 3D printed adapter to the shower piping
Electronic Mixer valve was developed to regulate the relation between hot and cold water to match user settings.
Need to buy hot water tank that maintains its temperature over time
Need to design and build the  hot water system with ininerator(write a new issue) and electrical resistence to mantain temperature inside the hot water tank.

**Comment by omerll** [comment]
Still in progress, last week where developing Desalination machine.
Need to buy hot water tank that maintains its temperature over time
Need to design and build the hot water system with ininerator(write a new issue) and electrical resistence to mantain temperature inside the hot water tank.

**Comment by siddiqss** [comment]
The mixer valve was tested but of the nature of construction of this type of valve contains 3 springs, restricts the flow too much for the jet pump to work correctly.

Changed the type of solution with 2 proportional water valves, 1 for hot and 1 for cold. This way the system is more reliable and more efficient because of lack of springs in the assembly. Currently building two custom proportional valves.

**Comment by omerll** [comment]
Ordered componentes for building 2 proportional valves, will arrive next thursday 1 of Dec

**Comment by omerll** [comment]
Proportional Valves arrived, circuit was made with OPAMP amplifier to adapt the signal from the microcontroller to the valve.

PCB circuit was drawn
![WhatsApp Image 2021-11-26 at 16 25 59](https://user-images.githubusercontent.com/84348234/144089840-5dca2bfc-ce23-4f39-b0d2-6546fcd4367b.jpeg)

**Comment by omerll** [comment]
Test with proportional valve :
https://user-images.githubusercontent.com/84348234/144089920-20bdff81-bda4-4e3e-988e-4e9ee33ef0e3.mp4

**Comment by omerll** [comment]
Programing & UI for shower


![WhatsApp Image 2021-12-01 at 23 15 12](https://user-images.githubusercontent.com/84348234/144459182-730f55b2-8ae5-4bea-9c87-4013b0e1755d.jpeg)
![WhatsApp Image 2021-12-01 at 23 15 12 (1)](https://user-images.githubusercontent.com/84348234/144459196-8c43988f-4bd3-410f-ad79-a005d0544ec1.jpeg)

**Comment by omerll** [comment]
Circuit was sucesfully build and tested

**Comment by omerll** [comment]
Test and demo on the shower temp control electronics and UI
https://user-images.githubusercontent.com/84348234/144461186-bf5ec975-626a-42ef-af33-514c699ca227.mp4

**Comment by siddiqss** [comment]
PID control algorithm was written as a custom automation and tuned for having desired dynamic response.
Control parameters P=2.5, I = 0.1667 and D=0.

A test was made having nice results, the system has a maximum overshoot of 4%. It's stabilized in the desired range.
Instant water heater was selected. Will be ordered and tested to maintain the temperature of the water tank constant.

**Comment by omerll** [comment]
Instant heater was orded, instaled and tested, it has a super efficient design on the heat exanger and burner, so we reduce the fuel consuption up to 78 % compared with traditional boilers, this device is from BOSCH, and was integrated with our system to heat water when cold cater flows through the hot water tank, and to support the incinerator system when here is not poop to burn.

Shower project hardware and software is done!
New to write new issue for NFC Ring integration (Sets the temperature and desired nozzle automatically)
New to write new issue for water proof tablet for the controls on the shower
New to write new issue for voice commands on integrate into the shower

**Comment by omerll** [comment]
https://user-images.githubusercontent.com/84348234/146037657-f3e45f43-8735-40fc-a900-809f55c3321a.mp4

**Comment by omerll** [comment]
![WhatsApp Image 2021-12-14 at 10 20 20](https://user-images.githubusercontent.com/84348234/146038002-9f09d605-feaa-41b1-9005-1553d7499a00.jpeg)
