### ISSUE TITLE
Build a Grey Water Treatment system to treat water from the shower

### ISSUE THREAD

**Issue by amitpujar** [oceanbuilders/smartpod#84]
Grey water - shower back to GWT system (endless shower). The system collects used water from the shower and processes it and pumps back to storage for reuse.

**Comment by omerll** [comment]
This issue is being solved by LOTIC. The company that is building the grey water treatment machine. I had a couple meetings with them and shared the techinical specs and requierments that we need for that system...... This should be closed.
