### ISSUE TITLE
Install and test - Black Water Treatment System (LoTic) 

### ISSUE THREAD

**Issue by amitpujar** [oceanbuilders/smartpod#85]
Black Water/Sewage Treatment Plant by vendoe LoTec

The system consists of utilities to separate solids from liquids, incinerator and a heat exchanger that can provide hot water in the Pod.

**Comment by omerll** [comment]
This issue is being solved by LOTIC. The company that is building the grey water treatment machine. I had a couple meetings with them and shared the techinical specs and requierments that we need for that system...... This should be closed.
