### ISSUE TITLE
Research and Order Lights for Testing

### ISSUE THREAD

**Issue by scottdear** [oceanbuilders/smartpod#9]
Order lights for testing and have them shipped to Nana Spot

Acceptance Criteria
-----------------------
1. A list of items needed w/ ATA/SSC numbering (work w/ Marcus)
2. Order Parts list with vendor part #'s

**Comment by scottdear** [comment]
@scottdear needs to review the shopping cart before pushing the big shiny red button:
![image](https://user-images.githubusercontent.com/4229319/117326178-4300c600-ae46-11eb-8d6c-1f7bf23662fd.png)

**Comment by angiedear** [comment]
![Uploading image.png…]()
