### ISSUE TITLE
Automate desalination machine

### ISSUE THREAD

**Issue by siddiqss** [oceanbuilders/smartpod#99]
Automate the following:
1. Low pressure pump
2. High pressure pump
3. Constant flow, variable pressure valve
4. Low pressure gauge and high pressure gauge
5. Flow meter
6. TDS meter

**Comment by siddiqss** [comment]
All the sensors were calibrated and tested with external equipment successfully.
The automation algorithm was working and has the protections and alerts for the actuators.

A bridge to home assistant was developed.
Will start working on documentation after Thursday.

**Comment by omerll** [comment]
Desalination machine first prototype is finished 100%. We will wait for feedback from the demo to make the final adjustments
New repo was written at oceanbuilders/desmachine

**Comment by omerll** [comment]
New Updates made to the desalination machine:
-3 led indicators where included to show the state of the des-machine (ON/OFF/RINSING/ MANTAINACE NEDEED) 

- Security stop botton was included  for emergency stop… On/ off the machine by hand 

- two float sensors where installed on the clean water tank 

The bottom one triggers the machine and the upper one stops the machine. This way the machine works just once a day constantly for 1:30 hours to 2 hours producing about 120L of water. This amount can be adjusted by the difference on height between the 2 sensors the more distance you put between them the more litters the machine produce per day 

- Rising stage added to the programming. Each time the process of making fresh water ends, the machine cleans 🧼 it self automatically to have longer maintaince intervals and more life span on the membrane and filters. Also you can see on the UI when the machine is on the RINSING mode 

- New power stage was installed with Solid state relays to increase the lifespan of the device from 2 years(normal relays) to 20 years with SSR.  Also led indicators where added for each device ( low pressure pump, high pressure pump, rinsing pump) to know when each device is powered on. This way makes it easier to troblueshoot

- the IOT Bridge was replaced to a new microcontroller that has Ethernet connection so we have more stable connection with the HA server. Also data was encrypted and with quality of service of 1 to ensure the communication between desalination machine and HA server is estable (confirms that messages arrived to the server)
